version: '3.7'

services:
  frontend:
    container_name: user-app
    build: ./client
    volumes:
      - './:/app'
      - '/app/node_modules'
      - './src:/app/src'
    ports:
      - 3000:3000
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true
    command: npm start
